### PR TITLE
Ability to override note style

### PR DESCRIPTION
**Pull request by clintharris**
Also a minor change to the README so the demo page loads Leaflet.

### CODE REVIEW

**Comment by atstp** [comment]
looks good, and thanks for the doc changes!

**Comment by clintharris** [comment]
Can you publish to npm?

**Comment by atstp** [comment]
ah, of course.  The new version's good to go :+1:

**Comment by atstp** [comment]
yeah, of course! [`0.3.1`](https://www.npmjs.com/package/leaflet-sleep) is good to go :+1:

**Pull request merged**
